version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: php:7.4-apache
      - image: mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: test
          MYSQL_DATABASE: equal
    working_directory: /var/www/html
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apt-get update && apt-get -y install git libzip-dev
            docker-php-ext-install pdo pdo_mysql mysqli zip
            docker-php-ext-enable mysqli
      - run:
          name: Clone equal repository
          command: git clone https://github.com/equalframework/equal.git
      - run:
          name: Copy files to the working directory
          command: cp -r equal/* /var/www/html/
      - run:
          name: Set permissions for 'run.php'
          command: chmod 755 run.php
      - run:
          name: Verify the presence and correct Access Rights of mandatory directories
          command: php run.php --do=test_fs-consistency
      - run:
          name: Verifying the Connectivity to the DBMS Service
          command: php run.php --do=test_db-connectivity
      - run:
          name: Creating an Empty Database
          command: php run.php --do=init_db
      - run:
          name: Initializing Core package with Demo Data
          command: php run.php --do=init_package --package=core --import=true
      - run:
          name: Running Test Units for the Core Package
          command: php run.php --do=test_package --package=core
      - run:
          name: Clone projectFlow repository
          command: |
            git clone https://github.com/alexandraYesbabylon/projectFlow.git projectFlow
            mv projectFlow packages
      - run:
          name: Initializing projectFlow package with Demo Data
          command: php run.php --do=init_package --package=projectFlow
      - run:
          name: Install MySQL Client
          command: |
            apt-get -y install mariadb-client
      - run:
          name: Execute SQL Queries
          command: |
            mysql --version
# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
