version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: php:7.4-apache
      - image: mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: test
          MYSQL_DATABASE: equal
    working_directory: /var/www/html
    steps:
      - checkout
      - run:
          name: Instalar dependencias y configurar PHP
          command: |
            apt-get update && apt-get -y install git libzip-dev
            docker-php-ext-install pdo pdo_mysql mysqli zip
            docker-php-ext-enable mysqli
            php --version
      - run:
          name: Clonar el repositorio
          command: git clone https://github.com/equalframework/equal.git

      # Copiar los archivos al directorio de trabajo
      - run:
          name: Copiar archivos al directorio de trabajo
          command: cp -r equal/* /var/www/html/

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
