version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: php:7.4-apache
      - image: mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: test
          MYSQL_DATABASE: equal
    working_directory: /var/www/html
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apt-get update && apt-get -y install git libzip-dev
            docker-php-ext-install pdo pdo_mysql mysqli zip
            docker-php-ext-enable mysqli
      - run:
          name: Clone equal repository
          command: git clone https://github.com/equalframework/equal.git
      - run:
          name: Copy files to the working directory
          command: cp -r equal/* /var/www/html/
      - run:
          name: Set permissions for 'run.php'
          command: chmod 755 run.php
      - run:
          name: Verify the presence and correct Access Rights of mandatory directories
          command: php run.php --do=test_fs-consistency
      - run:
          name: Verifying the Connectivity to the DBMS Service
          command: php run.php --do=test_db-connectivity
      - run:
          name: Creating an Empty Database
          command: php run.php --do=init_db
      - run:
          name: Initializing package Core with Demo Data
          command: php run.php --do=init_package --package=core --import=true
      - run:
          name: Running Test Units for the Core Package
          command: php run.php --do=test_package --package=core
      - run: cd packages
      - run: mkdir projectFlow
      - run: ls -lah packages
      - run: git clone https://github.com/alexandraYesbabylon/projectFlow.git projectFlow
      - run: ls -lah packages
# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
