version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
    - image: php:7.4-apache

    - image: mysql:5.7
      environment:
        MYSQL_ROOT_PASSWORD: test
        MYSQL_DATABASE: equal

    steps:
      # install dependencies
      - checkout
      - run: apt-get update && apt-get -y install git libzip-dev
      - run: docker-php-ext-install pdo pdo_mysql mysqli zip
      - run: docker-php-ext-enable mysqli
      - run: php --version
      # clone equal
      - run: git clone https://github.com/equalframework/equal.git
      - run: git config --global --add safe.directory /var/www/html
      - run: echo success

      # create an empty database
      - run: php run.php --do=init_db

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
