version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
    - image: php:7.4-apache

    - image: mysql:5.7
      environment:
        MYSQL_ROOT_PASSWORD: test
        MYSQL_DATABASE: equal

#    working_directory: /var/www/html

    steps:
      # install dependencies
      - run: apt-get update && apt-get -y install git libzip-dev
      - run: docker-php-ext-install pdo pdo_mysql mysqli zip
      - run: docker-php-ext-enable mysqli
      - run: php --version
      - run: git clone https://github.com/equalframework/equal.git
      - run: rm -rf /var/www/html
      - run: mv equal /var/www/html
      - run: cd /var/www/html
      - run: ls -lah /var/www/html
      - run: chmod 755 run.php
      - run: ls -lah /var/www/html
      #- run: php run.php --do=test_fs-consistency
        # clone equal

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
